# Generated by Django 4.1.3 on 2022-11-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='users', max_length=50)),
                ('slug', models.CharField(blank=True, max_length=50, unique=True)),
                ('emails', models.CharField(blank=True, default='users@gmail.com', max_length=50)),
                ('password', models.CharField(blank=True, default='users', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
